<?php

return [
    [
        'key' => 'monitoring-data',
        'label' => 'Monitoring Data',
        'description' => 'Pantau statistik pengajuan dan aktivitas',
        'route' => 'admin.dashboard',
        'group' => 'Monitoring',
        'roles' => ['super_admin', 'verifikator', 'operator'],
    ],
    [
        'key' => 'daftar-pengajuan',
        'label' => 'Daftar Pengajuan',
        'description' => 'Lihat seluruh pengajuan aktif',
        'route' => 'admin.pengajuan.index',
        'group' => 'Pengajuan',
        'roles' => ['super_admin', 'verifikator', 'operator', 'lay_person'],
    ],
    [
        'key' => 'verifikasi-pengajuan',
        'label' => 'Verifikasi Pengajuan',
        'description' => 'Kelola proses verifikasi proposal',
        'route' => 'admin.verifications.index',
        'group' => 'Pengajuan',
        'roles' => ['super_admin', 'verifikator'],
    ],
    [
        'key' => 'export-data',
        'label' => 'Export Data',
        'description' => 'Unduh laporan pengajuan dan user',
        'route' => 'admin.exports.index',
        'group' => 'Operasional',
        'roles' => ['super_admin', 'verifikator', 'operator'],
    ],
    [
        'key' => 'manajemen-user',
        'label' => 'Manajemen User',
        'description' => 'Kelola user terdaftar',
        'route' => 'admin.users.index',
        'group' => 'Pengguna',
        'roles' => ['super_admin', 'verifikator', 'operator'],
    ],
    [
        'key' => 'verifikasi-user',
        'label' => 'Verifikasi Registrasi',
        'description' => 'Review dan setujui registrasi baru',
        'route' => 'admin.registrations.index',
        'group' => 'Pengguna',
        'roles' => ['super_admin', 'verifikator', 'operator'],
    ],
    [
        'key' => 'plotting-lay-person',
        'label' => 'Plotting Lay Person',
        'description' => 'Tetapkan lay person ke pengajuan',
        'route' => 'admin.plotting.index',
        'group' => 'Operasional',
        'roles' => ['super_admin', 'verifikator'],
    ],
    [
        'key' => 'lay-person-assignments',
        'label' => 'Penugasan Anda',
        'description' => 'Daftar pengajuan yang perlu ditinjau',
        'route' => 'lay-person.assignments',
        'group' => 'Lay Person',
        'roles' => ['lay_person'],
    ],
    [
        'key' => 'lay-person-forms',
        'label' => 'Form Penilaian',
        'description' => 'Isi form sesuai penugasan',
        'route' => 'lay-person.forms',
        'group' => 'Lay Person',
        'roles' => ['lay_person'],
    ],
    [
        'key' => 'pengajuan-baru',
        'label' => 'Pengajuan Baru',
        'description' => 'Kirim pengajuan etik baru',
        'route' => 'pengajuan-baru.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
    [
        'key' => 'pengajuan-perbaikan',
        'label' => 'Pengajuan Perbaikan',
        'description' => 'Kirim revisi dari proposal',
        'route' => 'perbaikan.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
    [
        'key' => 'pengajuan-amandemen',
        'label' => 'Pengajuan Amandemen',
        'description' => 'Ajukan perubahan protokol',
        'route' => 'amandemen.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
    [
        'key' => 'perpanjangan-penelitian',
        'label' => 'Perpanjangan Penelitian',
        'description' => 'Ajukan perpanjangan izin penelitian',
        'route' => 'perpanjangan.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
    [
        'key' => 'laporan-akhir',
        'label' => 'Laporan Akhir',
        'description' => 'Laporkan hasil penelitian',
        'route' => 'laporan-akhir.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
    [
        'key' => 'ktd-sae',
        'label' => 'KTD & SAE',
        'description' => 'Form kejadian tak terduga/SAE',
        'route' => 'ktd-sae.index',
        'group' => 'Pengusul Etik',
        'roles' => ['pengusul_etik'],
    ],
];
